services:
  app_proxy:
    environment:
      APP_HOST: corbee-calibre_web_1
      APP_PORT: 8083
      PROXY_AUTH_ADD: "false"

  web:
    image: crocodilestick/calibre-web-automated:latest
    user: "911:911"
    restart: on-failure
    environment:
      - PUID=911
      - PGID=911
      - TZ=EEST
      - UMASK=022
      - USER_ID=911
      - GROUP_ID=911
    volumes:
      - ${APP_DATA_DIR}/data/config:/config 
      - ${APP_DATA_DIR}/data/ingest:/cwa-book-ingest
      - ${UMBREL_ROOT}/data/storage/downloads/library:/calibre-library 
    ports:
      - 8083:8083
